spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dataschool
    username: root
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
      default-page-size: 200

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    try-it-out-enabled: true

